import { Metadata } from "next"
import "./styles/global.css";
import Navigation from "./components/navigation"

export const metadata: Metadata = {
  title: {
    template: "%s | New York Times Best Seller",
    default: "New York Times Best Seller"
  },
  description: 'The Homepage to introduce The New York Times Best Seller. Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Navigation />
        {children}
      </body>
    </html>
  )
}
